apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helpers.s3ConfigMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ template "helpers.chart" . }}
    release: {{ .Release.Name }}
data:
  endPoint: {{ .Values.configuration.values.s3EndPoint }}
  bucket: {{ .Values.configuration.values.s3Bucket }}
  