{{- if not .Values.secrets.index.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helpers.indexSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ template "helpers.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  snellerIndexKey: {{ (include "helpers.snellerIndexKey" .) | b64enc | quote }}
  {{ else }}
  snellerIndexKey: {{ (lookup "v1" "Secret" .Release.Namespace (include "helpers.indexSecretName" .)).data.snellerIndexKey }}
  {{ end }}  
{{- end}}