{{- if not .Values.secrets.token.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helpers.tokenSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ template "helpers.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  snellerToken: {{ (include "helpers.snellerToken" .) | b64enc | quote }}
  {{ else }}
  snellerToken: {{ (lookup "v1" "Secret" .Release.Namespace (include "helpers.tokenSecretName" .)).data.snellerToken }}
  {{ end }}  
{{- end}}