replicas: 4
resources:
        requests:
                memory: 1Gi
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  path: /
  hosts:
    - kubernetes-minio.sneller-dev.io
  tls:
    - secretName: kubernetes-minio-tls
      hosts:
        - kubernetes-minio.sneller-dev.io
