nameOverride: ""
fullnameOverride: ""

snellerd:
  #name: snellerd
  replicaCount: 3
  repository: 671229366946.dkr.ecr.us-east-1.amazonaws.com/sneller/snellerd
  tag: latest
  pullPolicy: IfNotPresent
  ports:
    snellerd: 8000
    internode: 8001
  maxCacheDirSize: 64Mi
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  serviceLabels: {}
  serviceAnnotations: {}
  headlessServiceLabels: {}
  headlessServiceAnnotations: {}

sdb:
  #name: sdb
  repository: 671229366946.dkr.ecr.us-east-1.amazonaws.com/sneller/sdb
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  # ingressClassName: ""
  hosts: []
  tls: []
  #  - secretName: sneller-tls
  #    hosts:
  #      - sneller-example.local  
  annotations: {}

secrets:
  s3:
    useExistingSecret: false
    #secretName: sneller-aws
    values:
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
  token:
    useExistingSecret: false
    #secretName: sneller-token
    values:
      snellerToken:        # When it's empty, then a random Sneller token will be created
  index:
    useExistingSecret: false
    #secretName: sneller-index
    values:
      snellerIndexKey: 4AiJmIzLvMAP8A/1XdmbuzdwDduxHdu4hVRO7//7vd8=

configuration:
  #name: 
  values:
    s3EndPoint: http://minio:9000
    s3Bucket: s3://test/
